
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddMoneyEffectConfig : ExpeditionEffectConfig
{
    public AddMoneyEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["operation"].IsNumber) { throw new SerializationException(); }  Operation = (Gameplay.Expedition.EnumExpeditionRewardOperation)_buf["operation"].AsInt; }
        { if(!_buf["money"].IsObject) { throw new SerializationException(); }  Money = global::GameConfig.Gameplay.Expedition.ExpeditionScaledValueConfig.DeserializeExpeditionScaledValueConfig(_buf["money"]);  }
    }

    public static AddMoneyEffectConfig DeserializeAddMoneyEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddMoneyEffectConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardOperation Operation;
    public readonly Gameplay.Expedition.ExpeditionScaledValueConfig Money;
   
    public const int __ID__ = -625639017;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Money?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "operation:" + Operation + ","
        + "money:" + Money + ","
        + "}";
    }
}
}

