
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddMoneyEffectConfig : ExpeditionEffectConfig
{
    public AddMoneyEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["money_delta"].IsNumber) { throw new SerializationException(); }  MoneyDelta = _buf["money_delta"]; }
    }

    public static AddMoneyEffectConfig DeserializeAddMoneyEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddMoneyEffectConfig(_buf);
    }

    public readonly int MoneyDelta;
   
    public const int __ID__ = -625639017;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "moneyDelta:" + MoneyDelta + ","
        + "}";
    }
}
}

