
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleExpEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleExpEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["exp_delta"].IsNumber) { throw new SerializationException(); }  ExpDelta = _buf["exp_delta"]; }
    }

    public static AddPlayerMarbleExpEffectConfig DeserializeAddPlayerMarbleExpEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleExpEffectConfig(_buf);
    }

    public readonly int ExpDelta;
   
    public const int __ID__ = -798641898;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "expDelta:" + ExpDelta + ","
        + "}";
    }
}
}

