
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["marble_count"].IsObject) { throw new SerializationException(); }  MarbleCount = global::GameConfig.Gameplay.Expedition.ExpeditionScaledValueConfig.DeserializeExpeditionScaledValueConfig(_buf["marble_count"]);  }
    }

    public static AddPlayerMarbleEffectConfig DeserializeAddPlayerMarbleEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleEffectConfig(_buf);
    }

    public readonly Gameplay.Expedition.ExpeditionScaledValueConfig MarbleCount;
   
    public const int __ID__ = 831192013;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        MarbleCount?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "marbleCount:" + MarbleCount + ","
        + "}";
    }
}
}

