
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleHpEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleHpEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["operation"].IsNumber) { throw new SerializationException(); }  Operation = (Gameplay.Expedition.EnumExpeditionRewardOperation)_buf["operation"].AsInt; }
        { if(!_buf["hp"].IsObject) { throw new SerializationException(); }  Hp = global::GameConfig.Gameplay.Expedition.ExpeditionScaledValueConfig.DeserializeExpeditionScaledValueConfig(_buf["hp"]);  }
    }

    public static AddPlayerMarbleHpEffectConfig DeserializeAddPlayerMarbleHpEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleHpEffectConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardOperation Operation;
    public readonly Gameplay.Expedition.ExpeditionScaledValueConfig Hp;
   
    public const int __ID__ = 1896911477;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Hp?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "operation:" + Operation + ","
        + "hp:" + Hp + ","
        + "}";
    }
}
}

