
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["marble_spawn_config"].IsObject) { throw new SerializationException(); }  MarbleSpawnConfig = global::GameConfig.Gameplay.Combat.MarbleSpawnConfig.DeserializeMarbleSpawnConfig(_buf["marble_spawn_config"]);  }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static AddPlayerMarbleEffectConfig DeserializeAddPlayerMarbleEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleEffectConfig(_buf);
    }

    public readonly Gameplay.Combat.MarbleSpawnConfig MarbleSpawnConfig;
    public readonly int Count;
   
    public const int __ID__ = 831192013;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        MarbleSpawnConfig?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "marbleSpawnConfig:" + MarbleSpawnConfig + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

