
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["marble_count_tier"].IsNumber) { throw new SerializationException(); }  MarbleCountTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["marble_count_tier"].AsInt; }
        { if(!_buf["marble_count_value"].IsNumber) { throw new SerializationException(); }  MarbleCountValue = _buf["marble_count_value"]; }
        { if(!_buf["marble_type_tier"].IsNumber) { throw new SerializationException(); }  MarbleTypeTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["marble_type_tier"].AsInt; }
        { if(!_buf["marble_type_value"].IsObject) { throw new SerializationException(); }  MarbleTypeValue = global::GameConfig.Gameplay.Combat.MarbleSpawnConfig.DeserializeMarbleSpawnConfig(_buf["marble_type_value"]);  }
    }

    public static AddPlayerMarbleEffectConfig DeserializeAddPlayerMarbleEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleEffectConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier MarbleCountTier;
    public readonly int MarbleCountValue;
    public readonly Gameplay.Expedition.EnumExpeditionRewardTier MarbleTypeTier;
    public readonly Gameplay.Combat.MarbleSpawnConfig MarbleTypeValue;
   
    public const int __ID__ = 831192013;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        MarbleTypeValue?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "marbleCountTier:" + MarbleCountTier + ","
        + "marbleCountValue:" + MarbleCountValue + ","
        + "marbleTypeTier:" + MarbleTypeTier + ","
        + "marbleTypeValue:" + MarbleTypeValue + ","
        + "}";
    }
}
}

