
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleExpEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleExpEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["tier"].IsNumber) { throw new SerializationException(); }  Tier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["tier"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static AddPlayerMarbleExpEffectConfig DeserializeAddPlayerMarbleExpEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleExpEffectConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier Tier;
    public readonly int Value;
   
    public const int __ID__ = -798641898;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "tier:" + Tier + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

