
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class AddPlayerMarbleHpEffectConfig : ExpeditionEffectConfig
{
    public AddPlayerMarbleHpEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["hp_delta"].IsNumber) { throw new SerializationException(); }  HpDelta = _buf["hp_delta"]; }
    }

    public static AddPlayerMarbleHpEffectConfig DeserializeAddPlayerMarbleHpEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.AddPlayerMarbleHpEffectConfig(_buf);
    }

    public readonly int HpDelta;
   
    public const int __ID__ = 1896911477;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "hpDelta:" + HpDelta + ","
        + "}";
    }
}
}

