
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ChangeEnvironmentEffectConfig : ExpeditionEffectConfig
{
    public ChangeEnvironmentEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["target_environment_config_id"].IsString) { throw new SerializationException(); }  TargetEnvironmentConfigId = _buf["target_environment_config_id"]; }
    }

    public static ChangeEnvironmentEffectConfig DeserializeChangeEnvironmentEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ChangeEnvironmentEffectConfig(_buf);
    }

    public readonly string TargetEnvironmentConfigId;
   
    public const int __ID__ = -480208239;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "targetEnvironmentConfigId:" + TargetEnvironmentConfigId + ","
        + "}";
    }
}
}

