
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class CounterAtLeastConditionConfig : ExpeditionConditionConfig
{
    public CounterAtLeastConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["counter_id"].IsString) { throw new SerializationException(); }  CounterId = _buf["counter_id"]; }
        { if(!_buf["min_value"].IsNumber) { throw new SerializationException(); }  MinValue = _buf["min_value"]; }
    }

    public static CounterAtLeastConditionConfig DeserializeCounterAtLeastConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.CounterAtLeastConditionConfig(_buf);
    }

    public readonly string CounterId;
    public readonly int MinValue;
   
    public const int __ID__ = -1672196354;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "counterId:" + CounterId + ","
        + "minValue:" + MinValue + ","
        + "}";
    }
}
}

