
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class DelayInsertNodeEffectConfig : ExpeditionEffectConfig
{
    public DelayInsertNodeEffectConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["passed_node_count"].IsNumber) { throw new SerializationException(); }  PassedNodeCount = _buf["passed_node_count"]; }
        { if(!_buf["node_type"].IsNumber) { throw new SerializationException(); }  NodeType = (Gameplay.Expedition.EnumExpeditionNodeType)_buf["node_type"].AsInt; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static DelayInsertNodeEffectConfig DeserializeDelayInsertNodeEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.DelayInsertNodeEffectConfig(_buf);
    }

    public readonly int PassedNodeCount;
    public readonly Gameplay.Expedition.EnumExpeditionNodeType NodeType;
    public readonly string Id;
   
    public const int __ID__ = -1040977204;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "passedNodeCount:" + PassedNodeCount + ","
        + "nodeType:" + NodeType + ","
        + "id:" + Id + ","
        + "}";
    }
}
}

