
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Expedition
{ 
    public enum EnumExpeditionRewardTier
    {
        /// <summary>
        /// tiny
        /// </summary>
        Tiny = 0,
        /// <summary>
        /// small
        /// </summary>
        Small = 1,
        /// <summary>
        /// medium
        /// </summary>
        Medium = 2,
        /// <summary>
        /// large
        /// </summary>
        Large = 3,
        /// <summary>
        /// huge
        /// </summary>
        Huge = 4,
    }

} 

