
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Expedition
{ 
    public enum EnumExpeditionRewardOperation
    {
        /// <summary>
        /// add
        /// </summary>
        Add = 0,
        /// <summary>
        /// sub
        /// </summary>
        Subtract = 1,
    }

} 

