
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Expedition
{ 
    public enum EnumExpeditionRoutePolicy
    {
        /// <summary>
        /// fixed_next
        /// </summary>
        FixedNext = 0,
        /// <summary>
        /// by_selected_option
        /// </summary>
        BySelectedOption = 1,
        /// <summary>
        /// by_conditions
        /// </summary>
        ByConditions = 2,
    }

} 

