
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Expedition
{ 
    public enum EnumExpeditionRewardProgressStage
    {
        /// <summary>
        /// early
        /// </summary>
        Early = 0,
        /// <summary>
        /// mid
        /// </summary>
        Mid = 1,
        /// <summary>
        /// late
        /// </summary>
        Late = 2,
    }

} 

