
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Expedition
{ 
    public enum EnumExpeditionNodeType
    {
        /// <summary>
        /// none
        /// </summary>
        None = 0,
        /// <summary>
        /// event
        /// </summary>
        Event = 1,
        /// <summary>
        /// combat
        /// </summary>
        Combat = 2,
    }

} 

