
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionConfig : Luban.BeanBase
{
    public ExpeditionConfig(JSONNode _buf) 
    {
        { if(!_buf["expedition_id"].IsString) { throw new SerializationException(); }  ExpeditionId = _buf["expedition_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["route"]; if(!__json0.IsArray) { throw new SerializationException(); } Route = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRouteNodeConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionRouteNodeConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionRouteNodeConfig.DeserializeExpeditionRouteNodeConfig(__e0);  }  Route.Add(__v0); }   }
    }

    public static ExpeditionConfig DeserializeExpeditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionConfig(_buf);
    }

    public readonly string ExpeditionId;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRouteNodeConfig> Route;
   
    public const int __ID__ = -1820934840;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Route) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "expeditionId:" + ExpeditionId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "route:" + Luban.StringUtil.CollectionToString(Route) + ","
        + "}";
    }
}
}

