
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionNodeTransitionConfig : Luban.BeanBase
{
    public ExpeditionNodeTransitionConfig(JSONNode _buf) 
    {
        { if(!_buf["transition_id"].IsString) { throw new SerializationException(); }  TransitionId = _buf["transition_id"]; }
        { if(!_buf["target_node_id"].IsString) { throw new SerializationException(); }  TargetNodeId = _buf["target_node_id"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { var __json0 = _buf["conditions"]; if(!__json0.IsArray) { throw new SerializationException(); } Conditions = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConditionConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionConditionConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionConditionConfig.DeserializeExpeditionConditionConfig(__e0);  }  Conditions.Add(__v0); }   }
    }

    public static ExpeditionNodeTransitionConfig DeserializeExpeditionNodeTransitionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionNodeTransitionConfig(_buf);
    }

    public readonly string TransitionId;
    public readonly string TargetNodeId;
    public readonly int Priority;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConditionConfig> Conditions;
   
    public const int __ID__ = 950644383;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Conditions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "transitionId:" + TransitionId + ","
        + "targetNodeId:" + TargetNodeId + ","
        + "priority:" + Priority + ","
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "}";
    }
}
}

