
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEventConfig : Luban.BeanBase
{
    public ExpeditionEventConfig(JSONNode _buf) 
    {
        { if(!_buf["event_id"].IsString) { throw new SerializationException(); }  EventId = _buf["event_id"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["options"]; if(!__json0.IsArray) { throw new SerializationException(); } Options = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEventOptionConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionEventOptionConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionEventOptionConfig.DeserializeExpeditionEventOptionConfig(__e0);  }  Options.Add(__v0); }   }
    }

    public static ExpeditionEventConfig DeserializeExpeditionEventConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEventConfig(_buf);
    }

    public readonly string EventId;
    public readonly string Title;
    public readonly string Description;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEventOptionConfig> Options;
   
    public const int __ID__ = 340205622;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Options) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "eventId:" + EventId + ","
        + "title:" + Title + ","
        + "description:" + Description + ","
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

