
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionOptionRouteConfig : Luban.BeanBase
{
    public ExpeditionOptionRouteConfig(JSONNode _buf) 
    {
        { if(!_buf["option_id"].IsString) { throw new SerializationException(); }  OptionId = _buf["option_id"]; }
        { if(!_buf["transition_id"].IsString) { throw new SerializationException(); }  TransitionId = _buf["transition_id"]; }
    }

    public static ExpeditionOptionRouteConfig DeserializeExpeditionOptionRouteConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionOptionRouteConfig(_buf);
    }

    public readonly string OptionId;
    public readonly string TransitionId;
   
    public const int __ID__ = 418226544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "optionId:" + OptionId + ","
        + "transitionId:" + TransitionId + ","
        + "}";
    }
}
}

