
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEventOptionConfig : Luban.BeanBase
{
    public ExpeditionEventOptionConfig(JSONNode _buf) 
    {
        { if(!_buf["option_id"].IsString) { throw new SerializationException(); }  OptionId = _buf["option_id"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["effect"].IsObject) { throw new SerializationException(); }  Effect = global::GameConfig.Gameplay.Expedition.ExpeditionEventEffectConfig.DeserializeExpeditionEventEffectConfig(_buf["effect"]);  }
    }

    public static ExpeditionEventOptionConfig DeserializeExpeditionEventOptionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEventOptionConfig(_buf);
    }

    public readonly string OptionId;
    public readonly string Title;
    public readonly string Description;
    public readonly Gameplay.Expedition.ExpeditionEventEffectConfig Effect;
   
    public const int __ID__ = 888480267;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Effect?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "optionId:" + OptionId + ","
        + "title:" + Title + ","
        + "description:" + Description + ","
        + "effect:" + Effect + ","
        + "}";
    }
}
}

