
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRouteNodeConfig : Luban.BeanBase
{
    public ExpeditionRouteNodeConfig(JSONNode _buf) 
    {
        { if(!_buf["node_id"].IsString) { throw new SerializationException(); }  NodeId = _buf["node_id"]; }
        { if(!_buf["node_type"].IsNumber) { throw new SerializationException(); }  NodeType = (Gameplay.Expedition.EnumExpeditionNodeType)_buf["node_type"].AsInt; }
        { if(!_buf["event_id"].IsString) { throw new SerializationException(); }  EventId = _buf["event_id"]; }
        { if(!_buf["combat_encounter_id"].IsString) { throw new SerializationException(); }  CombatEncounterId = _buf["combat_encounter_id"]; }
    }

    public static ExpeditionRouteNodeConfig DeserializeExpeditionRouteNodeConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRouteNodeConfig(_buf);
    }

    public readonly string NodeId;
    public readonly Gameplay.Expedition.EnumExpeditionNodeType NodeType;
    public readonly string EventId;
    public readonly string CombatEncounterId;
   
    public const int __ID__ = 435800007;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "nodeType:" + NodeType + ","
        + "eventId:" + EventId + ","
        + "combatEncounterId:" + CombatEncounterId + ","
        + "}";
    }
}
}

