
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionDynamicEnemyGroupConfig : Luban.BeanBase
{
    public ExpeditionDynamicEnemyGroupConfig(JSONNode _buf) 
    {
        { if(!_buf["count_tier"].IsNumber) { throw new SerializationException(); }  CountTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["count_tier"].AsInt; }
        { if(!_buf["level_tier"].IsNumber) { throw new SerializationException(); }  LevelTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["level_tier"].AsInt; }
    }

    public static ExpeditionDynamicEnemyGroupConfig DeserializeExpeditionDynamicEnemyGroupConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionDynamicEnemyGroupConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier CountTier;
    public readonly Gameplay.Expedition.EnumExpeditionRewardTier LevelTier;
   
    public const int __ID__ = 636630802;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "countTier:" + CountTier + ","
        + "levelTier:" + LevelTier + ","
        + "}";
    }
}
}

