
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public abstract partial class ExpeditionConditionConfig : Luban.BeanBase
{
    public ExpeditionConditionConfig(JSONNode _buf) 
    {
        { if(!_buf["summary"].IsString) { throw new SerializationException(); }  Summary = _buf["summary"]; }
    }

    public static ExpeditionConditionConfig DeserializeExpeditionConditionConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "HasFlagConditionConfig": return new Gameplay.Expedition.HasFlagConditionConfig(_buf);
            case "HasItemConditionConfig": return new Gameplay.Expedition.HasItemConditionConfig(_buf);
            case "HasChosenOptionConditionConfig": return new Gameplay.Expedition.HasChosenOptionConditionConfig(_buf);
            case "CounterAtLeastConditionConfig": return new Gameplay.Expedition.CounterAtLeastConditionConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string Summary;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "}";
    }
}
}

