
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRandomEventPoolEntryConfig : Luban.BeanBase
{
    public ExpeditionRandomEventPoolEntryConfig(JSONNode _buf) 
    {
        { if(!_buf["event_config_id"].IsString) { throw new SerializationException(); }  EventConfigId = _buf["event_config_id"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static ExpeditionRandomEventPoolEntryConfig DeserializeExpeditionRandomEventPoolEntryConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRandomEventPoolEntryConfig(_buf);
    }

    public readonly string EventConfigId;
    public readonly int Weight;
   
    public const int __ID__ = -849177849;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "eventConfigId:" + EventConfigId + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

