
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEnemyProfileConfig : Luban.BeanBase
{
    public ExpeditionEnemyProfileConfig(JSONNode _buf) 
    {
        { if(!_buf["enemy_profile_config_id"].IsString) { throw new SerializationException(); }  EnemyProfileConfigId = _buf["enemy_profile_config_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["lst_enemy_count"]; if(!__json0.IsArray) { throw new SerializationException(); } LstEnemyCount = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstEnemyCount.Add(__v0); }   }
        { var __json0 = _buf["lst_enemy_level"]; if(!__json0.IsArray) { throw new SerializationException(); } LstEnemyLevel = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstEnemyLevel.Add(__v0); }   }
    }

    public static ExpeditionEnemyProfileConfig DeserializeExpeditionEnemyProfileConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEnemyProfileConfig(_buf);
    }

    public readonly string EnemyProfileConfigId;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstEnemyCount;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstEnemyLevel;
   
    public const int __ID__ = -1633708887;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstEnemyCount) { _e?.ResolveRef(tables); }
        foreach (var _e in LstEnemyLevel) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "enemyProfileConfigId:" + EnemyProfileConfigId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "lstEnemyCount:" + Luban.StringUtil.CollectionToString(LstEnemyCount) + ","
        + "lstEnemyLevel:" + Luban.StringUtil.CollectionToString(LstEnemyLevel) + ","
        + "}";
    }
}
}

