
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEventEffectConfig : Luban.BeanBase
{
    public ExpeditionEventEffectConfig(JSONNode _buf) 
    {
        { if(!_buf["crystal_delta"].IsNumber) { throw new SerializationException(); }  CrystalDelta = _buf["crystal_delta"]; }
        { if(!_buf["exp_delta"].IsNumber) { throw new SerializationException(); }  ExpDelta = _buf["exp_delta"]; }
        { if(!_buf["hp_delta"].IsNumber) { throw new SerializationException(); }  HpDelta = _buf["hp_delta"]; }
        { if(!_buf["summary"].IsString) { throw new SerializationException(); }  Summary = _buf["summary"]; }
    }

    public static ExpeditionEventEffectConfig DeserializeExpeditionEventEffectConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEventEffectConfig(_buf);
    }

    public readonly int CrystalDelta;
    public readonly int ExpDelta;
    public readonly int HpDelta;
    public readonly string Summary;
   
    public const int __ID__ = -925430233;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "crystalDelta:" + CrystalDelta + ","
        + "expDelta:" + ExpDelta + ","
        + "hpDelta:" + HpDelta + ","
        + "summary:" + Summary + ","
        + "}";
    }
}
}

