
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionScaledValueConfig : Luban.BeanBase
{
    public ExpeditionScaledValueConfig(JSONNode _buf) 
    {
        { if(!_buf["reward_tier"].IsNumber) { throw new SerializationException(); }  RewardTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["reward_tier"].AsInt; }
    }

    public static ExpeditionScaledValueConfig DeserializeExpeditionScaledValueConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionScaledValueConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier RewardTier;
   
    public const int __ID__ = 1819703699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rewardTier:" + RewardTier + ","
        + "}";
    }
}
}

