
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEnemyMarbleConfig : Luban.BeanBase
{
    public ExpeditionEnemyMarbleConfig(JSONNode _buf) 
    {
        { if(!_buf["enemy_config_id"].IsString) { throw new SerializationException(); }  EnemyConfigId = _buf["enemy_config_id"]; }
        { if(!_buf["marble_config_id"].IsString) { throw new SerializationException(); }  MarbleConfigId = _buf["marble_config_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
    }

    public static ExpeditionEnemyMarbleConfig DeserializeExpeditionEnemyMarbleConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEnemyMarbleConfig(_buf);
    }

    public readonly string EnemyConfigId;
    public readonly string MarbleConfigId;
    public readonly string DisplayName;
    public readonly int Level;
   
    public const int __ID__ = 471875265;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyConfigId:" + EnemyConfigId + ","
        + "marbleConfigId:" + MarbleConfigId + ","
        + "displayName:" + DisplayName + ","
        + "level:" + Level + ","
        + "}";
    }
}
}

