
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRewardProfileConfig : Luban.BeanBase
{
    public ExpeditionRewardProfileConfig(JSONNode _buf) 
    {
        { if(!_buf["reward_profile_config_id"].IsString) { throw new SerializationException(); }  RewardProfileConfigId = _buf["reward_profile_config_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["lst_money"]; if(!__json0.IsArray) { throw new SerializationException(); } LstMoney = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstMoney.Add(__v0); }   }
        { var __json0 = _buf["lst_exp"]; if(!__json0.IsArray) { throw new SerializationException(); } LstExp = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstExp.Add(__v0); }   }
        { var __json0 = _buf["lst_hp"]; if(!__json0.IsArray) { throw new SerializationException(); } LstHp = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstHp.Add(__v0); }   }
        { var __json0 = _buf["lst_marble_count"]; if(!__json0.IsArray) { throw new SerializationException(); } LstMarbleCount = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionStageTierIntValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionStageTierIntValueConfig.DeserializeExpeditionStageTierIntValueConfig(__e0);  }  LstMarbleCount.Add(__v0); }   }
        { var __json0 = _buf["lst_recruit_candidate"]; if(!__json0.IsArray) { throw new SerializationException(); } LstRecruitCandidate = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRecruitRewardCandidateConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionRecruitRewardCandidateConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionRecruitRewardCandidateConfig.DeserializeExpeditionRecruitRewardCandidateConfig(__e0);  }  LstRecruitCandidate.Add(__v0); }   }
    }

    public static ExpeditionRewardProfileConfig DeserializeExpeditionRewardProfileConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRewardProfileConfig(_buf);
    }

    public readonly string RewardProfileConfigId;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstMoney;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstExp;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstHp;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionStageTierIntValueConfig> LstMarbleCount;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRecruitRewardCandidateConfig> LstRecruitCandidate;
   
    public const int __ID__ = -1508943082;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstMoney) { _e?.ResolveRef(tables); }
        foreach (var _e in LstExp) { _e?.ResolveRef(tables); }
        foreach (var _e in LstHp) { _e?.ResolveRef(tables); }
        foreach (var _e in LstMarbleCount) { _e?.ResolveRef(tables); }
        foreach (var _e in LstRecruitCandidate) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "rewardProfileConfigId:" + RewardProfileConfigId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "lstMoney:" + Luban.StringUtil.CollectionToString(LstMoney) + ","
        + "lstExp:" + Luban.StringUtil.CollectionToString(LstExp) + ","
        + "lstHp:" + Luban.StringUtil.CollectionToString(LstHp) + ","
        + "lstMarbleCount:" + Luban.StringUtil.CollectionToString(LstMarbleCount) + ","
        + "lstRecruitCandidate:" + Luban.StringUtil.CollectionToString(LstRecruitCandidate) + ","
        + "}";
    }
}
}

