
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionCombatEncounterConfig : Luban.BeanBase
{
    public ExpeditionCombatEncounterConfig(JSONNode _buf) 
    {
        { if(!_buf["combat_encounter_id"].IsString) { throw new SerializationException(); }  CombatEncounterId = _buf["combat_encounter_id"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["victory_crystal_reward"].IsNumber) { throw new SerializationException(); }  VictoryCrystalReward = _buf["victory_crystal_reward"]; }
        { if(!_buf["victory_exp_reward"].IsNumber) { throw new SerializationException(); }  VictoryExpReward = _buf["victory_exp_reward"]; }
        { var __json0 = _buf["enemy_marbles"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyMarbles = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEnemyMarbleConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionEnemyMarbleConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionEnemyMarbleConfig.DeserializeExpeditionEnemyMarbleConfig(__e0);  }  EnemyMarbles.Add(__v0); }   }
    }

    public static ExpeditionCombatEncounterConfig DeserializeExpeditionCombatEncounterConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionCombatEncounterConfig(_buf);
    }

    public readonly string CombatEncounterId;
    public readonly string Title;
    public readonly string Description;
    public readonly int VictoryCrystalReward;
    public readonly int VictoryExpReward;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEnemyMarbleConfig> EnemyMarbles;
   
    public const int __ID__ = -1862266373;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in EnemyMarbles) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "combatEncounterId:" + CombatEncounterId + ","
        + "title:" + Title + ","
        + "description:" + Description + ","
        + "victoryCrystalReward:" + VictoryCrystalReward + ","
        + "victoryExpReward:" + VictoryExpReward + ","
        + "enemyMarbles:" + Luban.StringUtil.CollectionToString(EnemyMarbles) + ","
        + "}";
    }
}
}

