
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionEnvironmentBattlefieldConfig : Luban.BeanBase
{
    public ExpeditionEnvironmentBattlefieldConfig(JSONNode _buf) 
    {
        { if(!_buf["battlefield_config_id"].IsString) { throw new SerializationException(); }  BattlefieldConfigId = _buf["battlefield_config_id"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static ExpeditionEnvironmentBattlefieldConfig DeserializeExpeditionEnvironmentBattlefieldConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionEnvironmentBattlefieldConfig(_buf);
    }

    public readonly string BattlefieldConfigId;
    public readonly int Weight;
   
    public const int __ID__ = -650125097;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "battlefieldConfigId:" + BattlefieldConfigId + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

