
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionTierIntValueConfig : Luban.BeanBase
{
    public ExpeditionTierIntValueConfig(JSONNode _buf) 
    {
        { if(!_buf["tier"].IsNumber) { throw new SerializationException(); }  Tier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["tier"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static ExpeditionTierIntValueConfig DeserializeExpeditionTierIntValueConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionTierIntValueConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier Tier;
    public readonly int Value;
   
    public const int __ID__ = 239011884;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tier:" + Tier + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

