
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public abstract partial class ExpeditionEffectConfig : Luban.BeanBase
{
    public ExpeditionEffectConfig(JSONNode _buf) 
    {
        { if(!_buf["summary"].IsString) { throw new SerializationException(); }  Summary = _buf["summary"]; }
    }

    public static ExpeditionEffectConfig DeserializeExpeditionEffectConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "AddMoneyEffectConfig": return new Gameplay.Expedition.AddMoneyEffectConfig(_buf);
            case "AddPlayerMarbleExpEffectConfig": return new Gameplay.Expedition.AddPlayerMarbleExpEffectConfig(_buf);
            case "AddPlayerMarbleHpEffectConfig": return new Gameplay.Expedition.AddPlayerMarbleHpEffectConfig(_buf);
            case "ChangeEnvironmentEffectConfig": return new Gameplay.Expedition.ChangeEnvironmentEffectConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string Summary;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "}";
    }
}
}

