
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRewardStageValueConfig : Luban.BeanBase
{
    public ExpeditionRewardStageValueConfig(JSONNode _buf) 
    {
        { if(!_buf["progress_stage"].IsNumber) { throw new SerializationException(); }  ProgressStage = (Gameplay.Expedition.EnumExpeditionRewardProgressStage)_buf["progress_stage"].AsInt; }
        { var __json0 = _buf["lst_value"]; if(!__json0.IsArray) { throw new SerializationException(); } LstValue = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRewardTierValueConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionRewardTierValueConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionRewardTierValueConfig.DeserializeExpeditionRewardTierValueConfig(__e0);  }  LstValue.Add(__v0); }   }
    }

    public static ExpeditionRewardStageValueConfig DeserializeExpeditionRewardStageValueConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRewardStageValueConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardProgressStage ProgressStage;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRewardTierValueConfig> LstValue;
   
    public const int __ID__ = -587733622;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstValue) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "progressStage:" + ProgressStage + ","
        + "lstValue:" + Luban.StringUtil.CollectionToString(LstValue) + ","
        + "}";
    }
}
}

