
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRandomEventPoolConfig : Luban.BeanBase
{
    public ExpeditionRandomEventPoolConfig(JSONNode _buf) 
    {
        { if(!_buf["random_event_pool_config_id"].IsString) { throw new SerializationException(); }  RandomEventPoolConfigId = _buf["random_event_pool_config_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["lst_event"]; if(!__json0.IsArray) { throw new SerializationException(); } LstEvent = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRandomEventPoolEntryConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionRandomEventPoolEntryConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionRandomEventPoolEntryConfig.DeserializeExpeditionRandomEventPoolEntryConfig(__e0);  }  LstEvent.Add(__v0); }   }
    }

    public static ExpeditionRandomEventPoolConfig DeserializeExpeditionRandomEventPoolConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRandomEventPoolConfig(_buf);
    }

    public readonly string RandomEventPoolConfigId;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionRandomEventPoolEntryConfig> LstEvent;
   
    public const int __ID__ = -754260305;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstEvent) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "randomEventPoolConfigId:" + RandomEventPoolConfigId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "lstEvent:" + Luban.StringUtil.CollectionToString(LstEvent) + ","
        + "}";
    }
}
}

