
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class ExpeditionRecruitRewardCandidateConfig : Luban.BeanBase
{
    public ExpeditionRecruitRewardCandidateConfig(JSONNode _buf) 
    {
        { if(!_buf["reward_tier"].IsNumber) { throw new SerializationException(); }  RewardTier = (Gameplay.Expedition.EnumExpeditionRewardTier)_buf["reward_tier"].AsInt; }
        { if(!_buf["marble_spawn_config"].IsObject) { throw new SerializationException(); }  MarbleSpawnConfig = global::GameConfig.Gameplay.Combat.MarbleSpawnConfig.DeserializeMarbleSpawnConfig(_buf["marble_spawn_config"]);  }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static ExpeditionRecruitRewardCandidateConfig DeserializeExpeditionRecruitRewardCandidateConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.ExpeditionRecruitRewardCandidateConfig(_buf);
    }

    public readonly Gameplay.Expedition.EnumExpeditionRewardTier RewardTier;
    public readonly Gameplay.Combat.MarbleSpawnConfig MarbleSpawnConfig;
    public readonly int Weight;
   
    public const int __ID__ = 2459742;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MarbleSpawnConfig?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "rewardTier:" + RewardTier + ","
        + "marbleSpawnConfig:" + MarbleSpawnConfig + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

