
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class HasChosenOptionConditionConfig : ExpeditionConditionConfig
{
    public HasChosenOptionConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["option_id"].IsString) { throw new SerializationException(); }  OptionId = _buf["option_id"]; }
    }

    public static HasChosenOptionConditionConfig DeserializeHasChosenOptionConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.HasChosenOptionConditionConfig(_buf);
    }

    public readonly string OptionId;
   
    public const int __ID__ = -1099723615;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "optionId:" + OptionId + ","
        + "}";
    }
}
}

