
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class HasFlagConditionConfig : ExpeditionConditionConfig
{
    public HasFlagConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["flag_id"].IsString) { throw new SerializationException(); }  FlagId = _buf["flag_id"]; }
    }

    public static HasFlagConditionConfig DeserializeHasFlagConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.HasFlagConditionConfig(_buf);
    }

    public readonly string FlagId;
   
    public const int __ID__ = -468075492;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "flagId:" + FlagId + ","
        + "}";
    }
}
}

