
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class HasItemConditionConfig : ExpeditionConditionConfig
{
    public HasItemConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
    }

    public static HasItemConditionConfig DeserializeHasItemConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.HasItemConditionConfig(_buf);
    }

    public readonly string ItemId;
   
    public const int __ID__ = -38101611;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "itemId:" + ItemId + ","
        + "}";
    }
}
}

