
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class NotConditionConfig : ExpeditionConditionConfig
{
    public NotConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["condition"].IsObject) { throw new SerializationException(); }  Condition = global::GameConfig.Gameplay.Expedition.ExpeditionConditionConfig.DeserializeExpeditionConditionConfig(_buf["condition"]);  }
    }

    public static NotConditionConfig DeserializeNotConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.NotConditionConfig(_buf);
    }

    public readonly Gameplay.Expedition.ExpeditionConditionConfig Condition;
   
    public const int __ID__ = 1510720847;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Condition?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "condition:" + Condition + ","
        + "}";
    }
}
}

