
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public sealed partial class OrConditionConfig : ExpeditionConditionConfig
{
    public OrConditionConfig(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["conditions"]; if(!__json0.IsArray) { throw new SerializationException(); } Conditions = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConditionConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Expedition.ExpeditionConditionConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Expedition.ExpeditionConditionConfig.DeserializeExpeditionConditionConfig(__e0);  }  Conditions.Add(__v0); }   }
    }

    public static OrConditionConfig DeserializeOrConditionConfig(JSONNode _buf)
    {
        return new Gameplay.Expedition.OrConditionConfig(_buf);
    }

    public readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConditionConfig> Conditions;
   
    public const int __ID__ = -1986410795;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        foreach (var _e in Conditions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "summary:" + Summary + ","
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "}";
    }
}
}

