
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public partial class TbExpedition
{
    private readonly System.Collections.Generic.Dictionary<string, Gameplay.Expedition.ExpeditionConfig> _dataMap;
    private readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConfig> _dataList;
    
    public TbExpedition(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Gameplay.Expedition.ExpeditionConfig>(count);
        _dataList = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Gameplay.Expedition.ExpeditionConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Gameplay.Expedition.ExpeditionConfig.DeserializeExpeditionConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ExpeditionConfigId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Gameplay.Expedition.ExpeditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Gameplay.Expedition.ExpeditionConfig> DataList => _dataList;

    public Gameplay.Expedition.ExpeditionConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gameplay.Expedition.ExpeditionConfig Get(string key) => _dataMap[key];
    public Gameplay.Expedition.ExpeditionConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

