
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Expedition
{
public partial class TbExpeditionEvent
{
    private readonly System.Collections.Generic.Dictionary<string, Gameplay.Expedition.ExpeditionEventConfig> _dataMap;
    private readonly System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEventConfig> _dataList;
    
    public TbExpeditionEvent(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Gameplay.Expedition.ExpeditionEventConfig>(count);
        _dataList = new System.Collections.Generic.List<Gameplay.Expedition.ExpeditionEventConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Gameplay.Expedition.ExpeditionEventConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Gameplay.Expedition.ExpeditionEventConfig.DeserializeExpeditionEventConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EventId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Gameplay.Expedition.ExpeditionEventConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Gameplay.Expedition.ExpeditionEventConfig> DataList => _dataList;

    public Gameplay.Expedition.ExpeditionEventConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gameplay.Expedition.ExpeditionEventConfig Get(string key) => _dataMap[key];
    public Gameplay.Expedition.ExpeditionEventConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

