
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Initial
{
public sealed partial class InitialConfig : Luban.BeanBase
{
    public InitialConfig(JSONNode _buf) 
    {
        { if(!_buf["camp_config_id"].IsString) { throw new SerializationException(); }  CampConfigId = _buf["camp_config_id"]; }
    }

    public static InitialConfig DeserializeInitialConfig(JSONNode _buf)
    {
        return new Gameplay.Initial.InitialConfig(_buf);
    }

    public readonly string CampConfigId;
   
    public const int __ID__ = -300273516;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "campConfigId:" + CampConfigId + ","
        + "}";
    }
}
}

