
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Initial
{
public partial class TbInitial
{

     private readonly Gameplay.Initial.InitialConfig _data;

     public Gameplay.Initial.InitialConfig Data => _data;

    public TbInitial(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::GameConfig.Gameplay.Initial.InitialConfig.DeserializeInitialConfig(_buf[0]);  }
    }


     public string CampConfigId => _data.CampConfigId;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

