
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class AbilityTimingConfig : Luban.BeanBase
{
    public AbilityTimingConfig(JSONNode _buf) 
    {
    }

    public static AbilityTimingConfig DeserializeAbilityTimingConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "FixedAbilityTimingConfig": return new Gameplay.Combat.FixedAbilityTimingConfig(_buf);
            case "RandomRangeAbilityTimingConfig": return new Gameplay.Combat.RandomRangeAbilityTimingConfig(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

