
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ArmorLevelConfig : EquipmentLevelConfig
{
    public ArmorLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["armor"].IsObject) { throw new SerializationException(); }  Armor = global::GameConfig.Gameplay.Combat.EquipmentAbilityConfig.DeserializeEquipmentAbilityConfig(_buf["armor"]);  }
    }

    public static ArmorLevelConfig DeserializeArmorLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ArmorLevelConfig(_buf);
    }

    public readonly Gameplay.Combat.EquipmentAbilityConfig Armor;
   
    public const int __ID__ = -1928026823;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Armor?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "mount:" + Mount + ","
        + "broken:" + Broken + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "armor:" + Armor + ","
        + "}";
    }
}
}

