
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ArmorReduceDamageAbilityConfig : EquipmentAbilityConfig
{
    public ArmorReduceDamageAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
    }

    public static ArmorReduceDamageAbilityConfig DeserializeArmorReduceDamageAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ArmorReduceDamageAbilityConfig(_buf);
    }

   
    public const int __ID__ = -558355798;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}

}

