
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ArmorAbsorbDamageAbilityConfig : EquipmentAbilityConfig
{
    public ArmorAbsorbDamageAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
    }

    public static ArmorAbsorbDamageAbilityConfig DeserializeArmorAbsorbDamageAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ArmorAbsorbDamageAbilityConfig(_buf);
    }

   
    public const int __ID__ = 1532287875;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}

}

