
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class BowAimAbilityConfig : EquipmentAbilityConfig
{
    public BowAimAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["rotate_speed"].IsNumber) { throw new SerializationException(); }  RotateSpeed = _buf["rotate_speed"]; }
        { if(!_buf["aim_angle"].IsNumber) { throw new SerializationException(); }  AimAngle = _buf["aim_angle"]; }
    }

    public static BowAimAbilityConfig DeserializeBowAimAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.BowAimAbilityConfig(_buf);
    }

    public readonly float RotateSpeed;
    public readonly float AimAngle;
   
    public const int __ID__ = 203453535;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "rotateSpeed:" + RotateSpeed + ","
        + "aimAngle:" + AimAngle + ","
        + "}";
    }
}
}

