
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class BowFireAbilityConfig : EquipmentAbilityConfig
{
    public BowFireAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["arrow_count"].IsNumber) { throw new SerializationException(); }  ArrowCount = _buf["arrow_count"]; }
        { if(!_buf["arrow_interval"].IsNumber) { throw new SerializationException(); }  ArrowInterval = _buf["arrow_interval"]; }
        { if(!_buf["arrow_angle_step"].IsNumber) { throw new SerializationException(); }  ArrowAngleStep = _buf["arrow_angle_step"]; }
        { if(!_buf["shoot_type"].IsNumber) { throw new SerializationException(); }  ShootType = (Gameplay.Combat.EnumBowShootType)_buf["shoot_type"].AsInt; }
        { if(!_buf["projectile_config_id"].IsString) { throw new SerializationException(); }  ProjectileConfigId = _buf["projectile_config_id"]; }
        { if(!_buf["projectile_level"].IsNumber) { throw new SerializationException(); }  ProjectileLevel = _buf["projectile_level"]; }
    }

    public static BowFireAbilityConfig DeserializeBowFireAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.BowFireAbilityConfig(_buf);
    }

    public readonly int ArrowCount;
    public readonly float ArrowInterval;
    public readonly float ArrowAngleStep;
    public readonly Gameplay.Combat.EnumBowShootType ShootType;
    public readonly string ProjectileConfigId;
    public readonly int ProjectileLevel;
   
    public const int __ID__ = 811469022;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "arrowCount:" + ArrowCount + ","
        + "arrowInterval:" + ArrowInterval + ","
        + "arrowAngleStep:" + ArrowAngleStep + ","
        + "shootType:" + ShootType + ","
        + "projectileConfigId:" + ProjectileConfigId + ","
        + "projectileLevel:" + ProjectileLevel + ","
        + "}";
    }
}
}

