
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class BowLevelConfig : WeaponLevelConfig
{
    public BowLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["bow_aim"].IsObject) { throw new SerializationException(); }  BowAim = global::GameConfig.Gameplay.Combat.BowAimAbilityConfig.DeserializeBowAimAbilityConfig(_buf["bow_aim"]);  }
        { if(!_buf["bow_fire"].IsObject) { throw new SerializationException(); }  BowFire = global::GameConfig.Gameplay.Combat.BowFireAbilityConfig.DeserializeBowFireAbilityConfig(_buf["bow_fire"]);  }
    }

    public static BowLevelConfig DeserializeBowLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.BowLevelConfig(_buf);
    }

    public readonly Gameplay.Combat.BowAimAbilityConfig BowAim;
    public readonly Gameplay.Combat.BowFireAbilityConfig BowFire;
   
    public const int __ID__ = -1363365810;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        BowAim?.ResolveRef(tables);
        BowFire?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "mount:" + Mount + ","
        + "broken:" + Broken + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "calculateDamage:" + CalculateDamage + ","
        + "cooldown:" + Cooldown + ","
        + "bowAim:" + BowAim + ","
        + "bowFire:" + BowFire + ","
        + "}";
    }
}
}

