
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class CombatBattlefieldConfig : Luban.BeanBase
{
    public CombatBattlefieldConfig(JSONNode _buf) 
    {
        { if(!_buf["battlefield_config_id"].IsString) { throw new SerializationException(); }  BattlefieldConfigId = _buf["battlefield_config_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
    }

    public static CombatBattlefieldConfig DeserializeCombatBattlefieldConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.CombatBattlefieldConfig(_buf);
    }

    public readonly string BattlefieldConfigId;
    public readonly string Name;
    public readonly string Description;
   
    public const int __ID__ = -1563249602;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "battlefieldConfigId:" + BattlefieldConfigId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

