
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Combat
{ 
    public enum EnumBowShootType
    {
        /// <summary>
        /// sequential
        /// </summary>
        Sequential = 0,
        /// <summary>
        /// spread
        /// </summary>
        Spread = 1,
    }

} 

