
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Combat
{ 
    public enum EnumProjectileTrackingType
    {
        /// <summary>
        /// none
        /// </summary>
        None = 0,
        /// <summary>
        /// target
        /// </summary>
        Target = 1,
        /// <summary>
        /// point
        /// </summary>
        Point = 2,
    }

} 

