
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Combat
{ 
    public enum EnumEquipmentSlot
    {
        /// <summary>
        /// top
        /// </summary>
        Top = 0,
        /// <summary>
        /// left
        /// </summary>
        Left = 1,
        /// <summary>
        /// right
        /// </summary>
        Right = 2,
        /// <summary>
        /// bottom
        /// </summary>
        Bottom = 3,
        /// <summary>
        /// middle
        /// </summary>
        Middle = 4,
    }

} 

