
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Gameplay.Combat
{ 
    public enum EnumCombineType
    {
        /// <summary>
        /// combine
        /// </summary>
        Combine = 0,
        /// <summary>
        /// override
        /// </summary>
        Override = 1,
    }

} 

