
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class EquipAttachConfig : Luban.BeanBase
{
    public EquipAttachConfig(JSONNode _buf) 
    {
        { if(!_buf["config_id"].IsString) { throw new SerializationException(); }  ConfigId = _buf["config_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["slot"].IsNumber) { throw new SerializationException(); }  Slot = (Gameplay.Combat.EnumEquipmentSlot)_buf["slot"].AsInt; }
    }

    public static EquipAttachConfig DeserializeEquipAttachConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.EquipAttachConfig(_buf);
    }

    public readonly string ConfigId;
    public readonly int Level;
    public readonly Gameplay.Combat.EnumEquipmentSlot Slot;
   
    public const int __ID__ = -72329115;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "level:" + Level + ","
        + "slot:" + Slot + ","
        + "}";
    }
}

}

