
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class EquipmentAbilityConfig : Luban.BeanBase
{
    public EquipmentAbilityConfig(JSONNode _buf) 
    {
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
    }

    public static EquipmentAbilityConfig DeserializeEquipmentAbilityConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "SwordCollisionAttackAbilityConfig": return new Gameplay.Combat.SwordCollisionAttackAbilityConfig(_buf);
            case "ArmorReduceDamageAbilityConfig": return new Gameplay.Combat.ArmorReduceDamageAbilityConfig(_buf);
            case "ArmorAbsorbDamageAbilityConfig": return new Gameplay.Combat.ArmorAbsorbDamageAbilityConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Priority;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}
}

