
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class FixedAbilityTimingConfig : AbilityTimingConfig
{
    public FixedAbilityTimingConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["duration"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["auto_activate"].IsBoolean) { throw new SerializationException(); }  AutoActivate = _buf["auto_activate"]; }
    }

    public static FixedAbilityTimingConfig DeserializeFixedAbilityTimingConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.FixedAbilityTimingConfig(_buf);
    }

    public readonly float Duration;
    public readonly float Cooldown;
    public readonly bool AutoActivate;
   
    public const int __ID__ = 146767988;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "duration:" + Duration + ","
        + "cooldown:" + Cooldown + ","
        + "autoActivate:" + AutoActivate + ","
        + "}";
    }
}
}

