
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class MarbleAbilityConfig : Luban.BeanBase
{
    public MarbleAbilityConfig(JSONNode _buf) 
    {
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
    }

    public static MarbleAbilityConfig DeserializeMarbleAbilityConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "MarbleSyncScaleAbilityConfig": return new Gameplay.Combat.MarbleSyncScaleAbilityConfig(_buf);
            case "MarbleSyncMassAbilityConfig": return new Gameplay.Combat.MarbleSyncMassAbilityConfig(_buf);
            case "MarbleDamagePipelineAbilityConfig": return new Gameplay.Combat.MarbleDamagePipelineAbilityConfig(_buf);
            case "MarbleHealPipelineAbilityConfig": return new Gameplay.Combat.MarbleHealPipelineAbilityConfig(_buf);
            case "MarbleShieldHealPipelineAbilityConfig": return new Gameplay.Combat.MarbleShieldHealPipelineAbilityConfig(_buf);
            case "MarbleReceiveDamageAbilityConfig": return new Gameplay.Combat.MarbleReceiveDamageAbilityConfig(_buf);
            case "MarbleAddHealAbilityConfig": return new Gameplay.Combat.MarbleAddHealAbilityConfig(_buf);
            case "MarbleAddExpAbilityConfig": return new Gameplay.Combat.MarbleAddExpAbilityConfig(_buf);
            case "MarbleDeathAbilityConfig": return new Gameplay.Combat.MarbleDeathAbilityConfig(_buf);
            case "MarbleLevelUpAbilityConfig": return new Gameplay.Combat.MarbleLevelUpAbilityConfig(_buf);
            case "MarbleGetTargetAbilityConfig": return new Gameplay.Combat.MarbleGetTargetAbilityConfig(_buf);
            case "MarbleMovementAbilityConfig": return new Gameplay.Combat.MarbleMovementAbilityConfig(_buf);
            case "MarbleRotationAbilityConfig": return new Gameplay.Combat.MarbleRotationAbilityConfig(_buf);
            case "MarbleCloseToTargetAbilityConfig": return new Gameplay.Combat.MarbleCloseToTargetAbilityConfig(_buf);
            case "MarbleDefaultRotateAbilityConfig": return new Gameplay.Combat.MarbleDefaultRotateAbilityConfig(_buf);
            case "MarbleDashAbilityConfig": return new Gameplay.Combat.MarbleDashAbilityConfig(_buf);
            case "MarbleFaceTargetDirectionAbilityConfig": return new Gameplay.Combat.MarbleFaceTargetDirectionAbilityConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Priority;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}
}

