
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleLevelConfig : Luban.BeanBase
{
    public MarbleLevelConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["upgrade_exp"].IsNumber) { throw new SerializationException(); }  UpgradeExp = _buf["upgrade_exp"]; }
        { if(!_buf["sync_scale"].IsObject) { throw new SerializationException(); }  SyncScale = global::GameConfig.Gameplay.Combat.MarbleSyncScaleAbilityConfig.DeserializeMarbleSyncScaleAbilityConfig(_buf["sync_scale"]);  }
        { if(!_buf["sync_mass"].IsObject) { throw new SerializationException(); }  SyncMass = global::GameConfig.Gameplay.Combat.MarbleSyncMassAbilityConfig.DeserializeMarbleSyncMassAbilityConfig(_buf["sync_mass"]);  }
        { if(!_buf["damage_pipeline"].IsObject) { throw new SerializationException(); }  DamagePipeline = global::GameConfig.Gameplay.Combat.MarbleDamagePipelineAbilityConfig.DeserializeMarbleDamagePipelineAbilityConfig(_buf["damage_pipeline"]);  }
        { if(!_buf["heal_pipeline"].IsObject) { throw new SerializationException(); }  HealPipeline = global::GameConfig.Gameplay.Combat.MarbleHealPipelineAbilityConfig.DeserializeMarbleHealPipelineAbilityConfig(_buf["heal_pipeline"]);  }
        { if(!_buf["shield_heal_pipeline"].IsObject) { throw new SerializationException(); }  ShieldHealPipeline = global::GameConfig.Gameplay.Combat.MarbleShieldHealPipelineAbilityConfig.DeserializeMarbleShieldHealPipelineAbilityConfig(_buf["shield_heal_pipeline"]);  }
        { if(!_buf["receive_damage"].IsObject) { throw new SerializationException(); }  ReceiveDamage = global::GameConfig.Gameplay.Combat.MarbleReceiveDamageAbilityConfig.DeserializeMarbleReceiveDamageAbilityConfig(_buf["receive_damage"]);  }
        { if(!_buf["add_heal"].IsObject) { throw new SerializationException(); }  AddHeal = global::GameConfig.Gameplay.Combat.MarbleAddHealAbilityConfig.DeserializeMarbleAddHealAbilityConfig(_buf["add_heal"]);  }
        { if(!_buf["add_exp"].IsObject) { throw new SerializationException(); }  AddExp = global::GameConfig.Gameplay.Combat.MarbleAddExpAbilityConfig.DeserializeMarbleAddExpAbilityConfig(_buf["add_exp"]);  }
        { if(!_buf["death"].IsObject) { throw new SerializationException(); }  Death = global::GameConfig.Gameplay.Combat.MarbleDeathAbilityConfig.DeserializeMarbleDeathAbilityConfig(_buf["death"]);  }
        { if(!_buf["level_up"].IsObject) { throw new SerializationException(); }  LevelUp = global::GameConfig.Gameplay.Combat.MarbleLevelUpAbilityConfig.DeserializeMarbleLevelUpAbilityConfig(_buf["level_up"]);  }
        { if(!_buf["get_target"].IsObject) { throw new SerializationException(); }  GetTarget = global::GameConfig.Gameplay.Combat.MarbleGetTargetAbilityConfig.DeserializeMarbleGetTargetAbilityConfig(_buf["get_target"]);  }
        { if(!_buf["movement"].IsObject) { throw new SerializationException(); }  Movement = global::GameConfig.Gameplay.Combat.MarbleMovementAbilityConfig.DeserializeMarbleMovementAbilityConfig(_buf["movement"]);  }
        { if(!_buf["rotation"].IsObject) { throw new SerializationException(); }  Rotation = global::GameConfig.Gameplay.Combat.MarbleRotationAbilityConfig.DeserializeMarbleRotationAbilityConfig(_buf["rotation"]);  }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["shield"]; }
        { if(!_buf["defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["defense"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["mass"].IsNumber) { throw new SerializationException(); }  Mass = _buf["mass"]; }
        { if(!_buf["scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["scale"]; }
        { var __json0 = _buf["lst_equipment"]; if(!__json0.IsArray) { throw new SerializationException(); } LstEquipment = new System.Collections.Generic.List<Gameplay.Combat.EquipAttachConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Combat.EquipAttachConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Combat.EquipAttachConfig.DeserializeEquipAttachConfig(__e0);  }  LstEquipment.Add(__v0); }   }
        { var __json0 = _buf["lst_ability"]; if(!__json0.IsArray) { throw new SerializationException(); } LstAbility = new System.Collections.Generic.List<Gameplay.Combat.MarbleAbilityConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Combat.MarbleAbilityConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Combat.MarbleAbilityConfig.DeserializeMarbleAbilityConfig(__e0);  }  LstAbility.Add(__v0); }   }
    }

    public static MarbleLevelConfig DeserializeMarbleLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleLevelConfig(_buf);
    }

    public readonly int Level;
    public readonly int UpgradeExp;
    public readonly Gameplay.Combat.MarbleSyncScaleAbilityConfig SyncScale;
    public readonly Gameplay.Combat.MarbleSyncMassAbilityConfig SyncMass;
    public readonly Gameplay.Combat.MarbleDamagePipelineAbilityConfig DamagePipeline;
    public readonly Gameplay.Combat.MarbleHealPipelineAbilityConfig HealPipeline;
    public readonly Gameplay.Combat.MarbleShieldHealPipelineAbilityConfig ShieldHealPipeline;
    public readonly Gameplay.Combat.MarbleReceiveDamageAbilityConfig ReceiveDamage;
    public readonly Gameplay.Combat.MarbleAddHealAbilityConfig AddHeal;
    public readonly Gameplay.Combat.MarbleAddExpAbilityConfig AddExp;
    public readonly Gameplay.Combat.MarbleDeathAbilityConfig Death;
    public readonly Gameplay.Combat.MarbleLevelUpAbilityConfig LevelUp;
    public readonly Gameplay.Combat.MarbleGetTargetAbilityConfig GetTarget;
    public readonly Gameplay.Combat.MarbleMovementAbilityConfig Movement;
    public readonly Gameplay.Combat.MarbleRotationAbilityConfig Rotation;
    public readonly int Attack;
    public readonly int Hp;
    public readonly int Shield;
    public readonly int Defense;
    public readonly float Speed;
    public readonly float Mass;
    public readonly float Scale;
    public readonly System.Collections.Generic.List<Gameplay.Combat.EquipAttachConfig> LstEquipment;
    public readonly System.Collections.Generic.List<Gameplay.Combat.MarbleAbilityConfig> LstAbility;
   
    public const int __ID__ = -1055087977;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SyncScale?.ResolveRef(tables);
        SyncMass?.ResolveRef(tables);
        DamagePipeline?.ResolveRef(tables);
        HealPipeline?.ResolveRef(tables);
        ShieldHealPipeline?.ResolveRef(tables);
        ReceiveDamage?.ResolveRef(tables);
        AddHeal?.ResolveRef(tables);
        AddExp?.ResolveRef(tables);
        Death?.ResolveRef(tables);
        LevelUp?.ResolveRef(tables);
        GetTarget?.ResolveRef(tables);
        Movement?.ResolveRef(tables);
        Rotation?.ResolveRef(tables);
        foreach (var _e in LstEquipment) { _e?.ResolveRef(tables); }
        foreach (var _e in LstAbility) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "upgradeExp:" + UpgradeExp + ","
        + "syncScale:" + SyncScale + ","
        + "syncMass:" + SyncMass + ","
        + "damagePipeline:" + DamagePipeline + ","
        + "healPipeline:" + HealPipeline + ","
        + "shieldHealPipeline:" + ShieldHealPipeline + ","
        + "receiveDamage:" + ReceiveDamage + ","
        + "addHeal:" + AddHeal + ","
        + "addExp:" + AddExp + ","
        + "death:" + Death + ","
        + "levelUp:" + LevelUp + ","
        + "getTarget:" + GetTarget + ","
        + "movement:" + Movement + ","
        + "rotation:" + Rotation + ","
        + "attack:" + Attack + ","
        + "hp:" + Hp + ","
        + "shield:" + Shield + ","
        + "defense:" + Defense + ","
        + "speed:" + Speed + ","
        + "mass:" + Mass + ","
        + "scale:" + Scale + ","
        + "lstEquipment:" + Luban.StringUtil.CollectionToString(LstEquipment) + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "}";
    }
}
}

