
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleSpawnConfig : Luban.BeanBase
{
    public MarbleSpawnConfig(JSONNode _buf) 
    {
        { if(!_buf["marble_config_id"].IsString) { throw new SerializationException(); }  MarbleConfigId = _buf["marble_config_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["camp_config_id"].IsString) { throw new SerializationException(); }  CampConfigId = _buf["camp_config_id"]; }
    }

    public static MarbleSpawnConfig DeserializeMarbleSpawnConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleSpawnConfig(_buf);
    }

    public readonly string MarbleConfigId;
    public readonly int Level;
    public readonly string CampConfigId;
   
    public const int __ID__ = -527833778;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "marbleConfigId:" + MarbleConfigId + ","
        + "level:" + Level + ","
        + "campConfigId:" + CampConfigId + ","
        + "}";
    }
}
}

