
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleFaceTargetDirectionAbilityConfig : MarbleAbilityConfig
{
    public MarbleFaceTargetDirectionAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["combine_type"].IsNumber) { throw new SerializationException(); }  CombineType = (Gameplay.Combat.EnumCombineType)_buf["combine_type"].AsInt; }
        { if(!_buf["target_local_direction"].IsObject) { throw new SerializationException(); }  TargetLocalDirection = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf["target_local_direction"]));  }
        { if(!_buf["target_angular_speed"].IsNumber) { throw new SerializationException(); }  TargetAngularSpeed = _buf["target_angular_speed"]; }
        { if(!_buf["angular_acceleration"].IsNumber) { throw new SerializationException(); }  AngularAcceleration = _buf["angular_acceleration"]; }
        { if(!_buf["timing"].IsObject) { throw new SerializationException(); }  Timing = global::GameConfig.Gameplay.Combat.AbilityTimingConfig.DeserializeAbilityTimingConfig(_buf["timing"]);  }
    }

    public static MarbleFaceTargetDirectionAbilityConfig DeserializeMarbleFaceTargetDirectionAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleFaceTargetDirectionAbilityConfig(_buf);
    }

    public readonly Gameplay.Combat.EnumCombineType CombineType;
    public readonly UnityEngine.Vector2 TargetLocalDirection;
    public readonly float TargetAngularSpeed;
    public readonly float AngularAcceleration;
    public readonly Gameplay.Combat.AbilityTimingConfig Timing;
   
    public const int __ID__ = -1743928918;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Timing?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "combineType:" + CombineType + ","
        + "targetLocalDirection:" + TargetLocalDirection + ","
        + "targetAngularSpeed:" + TargetAngularSpeed + ","
        + "angularAcceleration:" + AngularAcceleration + ","
        + "timing:" + Timing + ","
        + "}";
    }
}
}

