
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleDashAbilityConfig : MarbleAbilityConfig
{
    public MarbleDashAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["combine_type"].IsNumber) { throw new SerializationException(); }  CombineType = (Gameplay.Combat.EnumCombineType)_buf["combine_type"].AsInt; }
        { if(!_buf["target_speed"].IsNumber) { throw new SerializationException(); }  TargetSpeed = _buf["target_speed"]; }
        { if(!_buf["acceleration"].IsNumber) { throw new SerializationException(); }  Acceleration = _buf["acceleration"]; }
        { if(!_buf["lock_direction_on_activate"].IsBoolean) { throw new SerializationException(); }  LockDirectionOnActivate = _buf["lock_direction_on_activate"]; }
        { if(!_buf["timing"].IsObject) { throw new SerializationException(); }  Timing = global::GameConfig.Gameplay.Combat.AbilityTimingConfig.DeserializeAbilityTimingConfig(_buf["timing"]);  }
    }

    public static MarbleDashAbilityConfig DeserializeMarbleDashAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleDashAbilityConfig(_buf);
    }

    public readonly Gameplay.Combat.EnumCombineType CombineType;
    public readonly float TargetSpeed;
    public readonly float Acceleration;
    public readonly bool LockDirectionOnActivate;
    public readonly Gameplay.Combat.AbilityTimingConfig Timing;
   
    public const int __ID__ = -893813621;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Timing?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "combineType:" + CombineType + ","
        + "targetSpeed:" + TargetSpeed + ","
        + "acceleration:" + Acceleration + ","
        + "lockDirectionOnActivate:" + LockDirectionOnActivate + ","
        + "timing:" + Timing + ","
        + "}";
    }
}
}

