
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleCloseToTargetAbilityConfig : MarbleAbilityConfig
{
    public MarbleCloseToTargetAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["close_distance"].IsNumber) { throw new SerializationException(); }  CloseDistance = _buf["close_distance"]; }
        { if(!_buf["target_speed"].IsNumber) { throw new SerializationException(); }  TargetSpeed = _buf["target_speed"]; }
        { if(!_buf["acceleration"].IsNumber) { throw new SerializationException(); }  Acceleration = _buf["acceleration"]; }
    }

    public static MarbleCloseToTargetAbilityConfig DeserializeMarbleCloseToTargetAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleCloseToTargetAbilityConfig(_buf);
    }

    public readonly float CloseDistance;
    public readonly float TargetSpeed;
    public readonly float Acceleration;
   
    public const int __ID__ = -2077236585;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "combineType:" + CombineType + ","
        + "closeDistance:" + CloseDistance + ","
        + "targetSpeed:" + TargetSpeed + ","
        + "acceleration:" + Acceleration + ","
        + "}";
    }
}

}

