
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class MarbleDefaultRotateAbilityConfig : MarbleAbilityConfig
{
    public MarbleDefaultRotateAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["target_angular_speed"].IsNumber) { throw new SerializationException(); }  TargetAngularSpeed = _buf["target_angular_speed"]; }
        { if(!_buf["angular_acceleration"].IsNumber) { throw new SerializationException(); }  AngularAcceleration = _buf["angular_acceleration"]; }
    }

    public static MarbleDefaultRotateAbilityConfig DeserializeMarbleDefaultRotateAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.MarbleDefaultRotateAbilityConfig(_buf);
    }

    public readonly float TargetAngularSpeed;
    public readonly float AngularAcceleration;
   
    public const int __ID__ = 1987229855;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "combineType:" + CombineType + ","
        + "targetAngularSpeed:" + TargetAngularSpeed + ","
        + "angularAcceleration:" + AngularAcceleration + ","
        + "}";
    }
}
}

