
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileMoveConfig : ProjectileAbilityConfig
{
    public ProjectileMoveConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
    }

    public static ProjectileMoveConfig DeserializeProjectileMoveConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileMoveConfig(_buf);
    }

    public readonly float Speed;
   
    public const int __ID__ = -1179026354;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "speed:" + Speed + ","
        + "}";
    }
}
}

