
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileTrackPointConfig : ProjectileTrackingConfig
{
    public ProjectileTrackPointConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["angular_speed"].IsNumber) { throw new SerializationException(); }  AngularSpeed = _buf["angular_speed"]; }
    }

    public static ProjectileTrackPointConfig DeserializeProjectileTrackPointConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileTrackPointConfig(_buf);
    }

    public readonly float AngularSpeed;
   
    public const int __ID__ = 1326220354;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "angularSpeed:" + AngularSpeed + ","
        + "}";
    }
}
}

