
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileTrackConfig : Luban.BeanBase
{
    public ProjectileTrackConfig(JSONNode _buf) 
    {
        { if(!_buf["tracking_type"].IsNumber) { throw new SerializationException(); }  TrackingType = (Gameplay.Combat.EnumProjectileTrackingType)_buf["tracking_type"].AsInt; }
        { if(!_buf["angular_speed"].IsNumber) { throw new SerializationException(); }  AngularSpeed = _buf["angular_speed"]; }
    }

    public static ProjectileTrackConfig DeserializeProjectileTrackConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileTrackConfig(_buf);
    }

    public readonly Gameplay.Combat.EnumProjectileTrackingType TrackingType;
    public readonly float AngularSpeed;
   
    public const int __ID__ = 1814660594;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "trackingType:" + TrackingType + ","
        + "angularSpeed:" + AngularSpeed + ","
        + "}";
    }
}
}

