
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class ProjectileTrackingConfig : ProjectileAbilityConfig
{
    public ProjectileTrackingConfig(JSONNode _buf)  : base(_buf) 
    {
    }

    public static ProjectileTrackingConfig DeserializeProjectileTrackingConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "ProjectileNoTrackingConfig": return new Gameplay.Combat.ProjectileNoTrackingConfig(_buf);
            case "ProjectileTrackTargetConfig": return new Gameplay.Combat.ProjectileTrackTargetConfig(_buf);
            case "ProjectileTrackPointConfig": return new Gameplay.Combat.ProjectileTrackPointConfig(_buf);
            default: throw new SerializationException();
        }
    }

   

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}
}

