
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileAbilityConfig : Luban.BeanBase
{
    public ProjectileAbilityConfig(JSONNode _buf) 
    {
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
    }

    public static ProjectileAbilityConfig DeserializeProjectileAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileAbilityConfig(_buf);
    }

    public readonly int Priority;
   
    public const int __ID__ = -1737074351;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}
}

