
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileConfig : Luban.BeanBase
{
    public ProjectileConfig(JSONNode _buf) 
    {
        { if(!_buf["config_id"].IsString) { throw new SerializationException(); }  ConfigId = _buf["config_id"]; }
        { var __json0 = _buf["lst_level_config"]; if(!__json0.IsArray) { throw new SerializationException(); } LstLevelConfig = new System.Collections.Generic.List<Gameplay.Combat.ProjectileLevelConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Combat.ProjectileLevelConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Combat.ProjectileLevelConfig.DeserializeProjectileLevelConfig(__e0);  }  LstLevelConfig.Add(__v0); }   }
    }

    public static ProjectileConfig DeserializeProjectileConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileConfig(_buf);
    }

    public readonly string ConfigId;
    public readonly System.Collections.Generic.List<Gameplay.Combat.ProjectileLevelConfig> LstLevelConfig;
   
    public const int __ID__ = 168057501;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstLevelConfig) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "lstLevelConfig:" + Luban.StringUtil.CollectionToString(LstLevelConfig) + ","
        + "}";
    }
}
}

