
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileKnockbackConfig : ProjectileAbilityConfig
{
    public ProjectileKnockbackConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["force"].IsNumber) { throw new SerializationException(); }  Force = _buf["force"]; }
    }

    public static ProjectileKnockbackConfig DeserializeProjectileKnockbackConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileKnockbackConfig(_buf);
    }

    public readonly float Force;
   
    public const int __ID__ = -1259163166;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "force:" + Force + ","
        + "}";
    }
}
}

