
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileLifetimeConfig : Luban.BeanBase
{
    public ProjectileLifetimeConfig(JSONNode _buf) 
    {
        { var _j = _buf["max_lifetime"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  MaxLifetime = _j; } } else { MaxLifetime = null; } }
    }

    public static ProjectileLifetimeConfig DeserializeProjectileLifetimeConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileLifetimeConfig(_buf);
    }

    public readonly int? MaxLifetime;
   
    public const int __ID__ = -2074794810;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "maxLifetime:" + MaxLifetime + ","
        + "}";
    }
}
}

