
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileDamageConfig : Luban.BeanBase
{
    public ProjectileDamageConfig(JSONNode _buf) 
    {
        { if(!_buf["is_damage_by_velocity"].IsBoolean) { throw new SerializationException(); }  IsDamageByVelocity = _buf["is_damage_by_velocity"]; }
        { if(!_buf["piercing_count"].IsNumber) { throw new SerializationException(); }  PiercingCount = _buf["piercing_count"]; }
    }

    public static ProjectileDamageConfig DeserializeProjectileDamageConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileDamageConfig(_buf);
    }

    public readonly bool IsDamageByVelocity;
    public readonly int PiercingCount;
   
    public const int __ID__ = 565252780;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "isDamageByVelocity:" + IsDamageByVelocity + ","
        + "piercingCount:" + PiercingCount + ","
        + "}";
    }
}
}

