
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class ProjectileLevelConfig : Luban.BeanBase
{
    public ProjectileLevelConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["move_ability"].IsObject) { throw new SerializationException(); }  MoveAbility = global::GameConfig.Gameplay.Combat.ProjectileMoveConfig.DeserializeProjectileMoveConfig(_buf["move_ability"]);  }
        { if(!_buf["damage_ability"].IsObject) { throw new SerializationException(); }  DamageAbility = global::GameConfig.Gameplay.Combat.ProjectileDamageConfig.DeserializeProjectileDamageConfig(_buf["damage_ability"]);  }
        { if(!_buf["lifetime"].IsObject) { throw new SerializationException(); }  Lifetime = global::GameConfig.Gameplay.Combat.ProjectileLifetimeConfig.DeserializeProjectileLifetimeConfig(_buf["lifetime"]);  }
        { if(!_buf["tracking"].IsObject) { throw new SerializationException(); }  Tracking = global::GameConfig.Gameplay.Combat.ProjectileTrackingConfig.DeserializeProjectileTrackingConfig(_buf["tracking"]);  }
        { var __json0 = _buf["lst_ability"]; if(!__json0.IsArray) { throw new SerializationException(); } LstAbility = new System.Collections.Generic.List<Gameplay.Combat.ProjectileAbilityConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Gameplay.Combat.ProjectileAbilityConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.Gameplay.Combat.ProjectileAbilityConfig.DeserializeProjectileAbilityConfig(__e0);  }  LstAbility.Add(__v0); }   }
    }

    public static ProjectileLevelConfig DeserializeProjectileLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.ProjectileLevelConfig(_buf);
    }

    public readonly int Level;
    public readonly string Name;
    public readonly Gameplay.Combat.ProjectileMoveConfig MoveAbility;
    public readonly Gameplay.Combat.ProjectileDamageConfig DamageAbility;
    public readonly Gameplay.Combat.ProjectileLifetimeConfig Lifetime;
    public readonly Gameplay.Combat.ProjectileTrackingConfig Tracking;
    public readonly System.Collections.Generic.List<Gameplay.Combat.ProjectileAbilityConfig> LstAbility;
   
    public const int __ID__ = -1953570453;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MoveAbility?.ResolveRef(tables);
        DamageAbility?.ResolveRef(tables);
        Lifetime?.ResolveRef(tables);
        Tracking?.ResolveRef(tables);
        foreach (var _e in LstAbility) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "moveAbility:" + MoveAbility + ","
        + "damageAbility:" + DamageAbility + ","
        + "lifetime:" + Lifetime + ","
        + "tracking:" + Tracking + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "}";
    }
}
}

