
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class ProjectileAbilityConfig : Luban.BeanBase
{
    public ProjectileAbilityConfig(JSONNode _buf) 
    {
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
    }

    public static ProjectileAbilityConfig DeserializeProjectileAbilityConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "ProjectileMoveConfig": return new Gameplay.Combat.ProjectileMoveConfig(_buf);
            case "ProjectileDamageConfig": return new Gameplay.Combat.ProjectileDamageConfig(_buf);
            case "ProjectileLifetimeConfig": return new Gameplay.Combat.ProjectileLifetimeConfig(_buf);
            case "ProjectileNoTrackingConfig": return new Gameplay.Combat.ProjectileNoTrackingConfig(_buf);
            case "ProjectileTrackTargetConfig": return new Gameplay.Combat.ProjectileTrackTargetConfig(_buf);
            case "ProjectileTrackPointConfig": return new Gameplay.Combat.ProjectileTrackPointConfig(_buf);
            case "ProjectileKnockbackConfig": return new Gameplay.Combat.ProjectileKnockbackConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Priority;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}
}

