
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class RandomRangeAbilityTimingConfig : AbilityTimingConfig
{
    public RandomRangeAbilityTimingConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["min_duration"].IsNumber) { throw new SerializationException(); }  MinDuration = _buf["min_duration"]; }
        { if(!_buf["max_duration"].IsNumber) { throw new SerializationException(); }  MaxDuration = _buf["max_duration"]; }
        { if(!_buf["min_cooldown"].IsNumber) { throw new SerializationException(); }  MinCooldown = _buf["min_cooldown"]; }
        { if(!_buf["max_cooldown"].IsNumber) { throw new SerializationException(); }  MaxCooldown = _buf["max_cooldown"]; }
        { if(!_buf["auto_activate"].IsBoolean) { throw new SerializationException(); }  AutoActivate = _buf["auto_activate"]; }
    }

    public static RandomRangeAbilityTimingConfig DeserializeRandomRangeAbilityTimingConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.RandomRangeAbilityTimingConfig(_buf);
    }

    public readonly float MinDuration;
    public readonly float MaxDuration;
    public readonly float MinCooldown;
    public readonly float MaxCooldown;
    public readonly bool AutoActivate;
   
    public const int __ID__ = -881444242;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "minDuration:" + MinDuration + ","
        + "maxDuration:" + MaxDuration + ","
        + "minCooldown:" + MinCooldown + ","
        + "maxCooldown:" + MaxCooldown + ","
        + "autoActivate:" + AutoActivate + ","
        + "}";
    }
}
}

