
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class SpearLevelConfig : WeaponLevelConfig
{
    public SpearLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["sword_collision_attack"].IsObject) { throw new SerializationException(); }  SwordCollisionAttack = global::GameConfig.Gameplay.Combat.SwordCollisionAttackAbilityConfig.DeserializeSwordCollisionAttackAbilityConfig(_buf["sword_collision_attack"]);  }
    }

    public static SpearLevelConfig DeserializeSpearLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.SpearLevelConfig(_buf);
    }

    public readonly Gameplay.Combat.SwordCollisionAttackAbilityConfig SwordCollisionAttack;
   
    public const int __ID__ = -1685667233;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        SwordCollisionAttack?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "mount:" + Mount + ","
        + "broken:" + Broken + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "calculateDamage:" + CalculateDamage + ","
        + "cooldown:" + Cooldown + ","
        + "swordCollisionAttack:" + SwordCollisionAttack + ","
        + "}";
    }
}
}

