
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class SwordLevelConfig : WeaponLevelConfig
{
    public SwordLevelConfig(JSONNode _buf)  : base(_buf) 
    {
    }

    public static SwordLevelConfig DeserializeSwordLevelConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.SwordLevelConfig(_buf);
    }

   
    public const int __ID__ = 1311567291;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "attack:" + Attack + ","
        + "isDamageByVelocity:" + IsDamageByVelocity + ","
        + "cooldown:" + Cooldown + ","
        + "}";
    }
}
}

