
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public partial class TbEquipment
{
    private readonly System.Collections.Generic.Dictionary<string, Gameplay.Combat.EquipmentConfig> _dataMap;
    private readonly System.Collections.Generic.List<Gameplay.Combat.EquipmentConfig> _dataList;
    
    public TbEquipment(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Gameplay.Combat.EquipmentConfig>(count);
        _dataList = new System.Collections.Generic.List<Gameplay.Combat.EquipmentConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Gameplay.Combat.EquipmentConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Gameplay.Combat.EquipmentConfig.DeserializeEquipmentConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ConfigId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Gameplay.Combat.EquipmentConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Gameplay.Combat.EquipmentConfig> DataList => _dataList;

    public Gameplay.Combat.EquipmentConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gameplay.Combat.EquipmentConfig Get(string key) => _dataMap[key];
    public Gameplay.Combat.EquipmentConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

