
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public abstract partial class WeaponLevelConfig : EquipmentLevelConfig
{
    public WeaponLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["calculate_damage"].IsObject) { throw new SerializationException(); }  CalculateDamage = global::GameConfig.Gameplay.Combat.WeaponCalculateDamageAbilityConfig.DeserializeWeaponCalculateDamageAbilityConfig(_buf["calculate_damage"]);  }
        { if(!_buf["cooldown"].IsObject) { throw new SerializationException(); }  Cooldown = global::GameConfig.Gameplay.Combat.WeaponCooldownAbilityConfig.DeserializeWeaponCooldownAbilityConfig(_buf["cooldown"]);  }
    }

    public static WeaponLevelConfig DeserializeWeaponLevelConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "SwordLevelConfig": return new Gameplay.Combat.SwordLevelConfig(_buf);
            case "BowLevelConfig": return new Gameplay.Combat.BowLevelConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly Gameplay.Combat.WeaponCalculateDamageAbilityConfig CalculateDamage;
    public readonly Gameplay.Combat.WeaponCooldownAbilityConfig Cooldown;
   

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        CalculateDamage?.ResolveRef(tables);
        Cooldown?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "calculateDamage:" + CalculateDamage + ","
        + "cooldown:" + Cooldown + ","
        + "}";
    }
}
}

