
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class WeaponCalculateDamageAbilityConfig : EquipmentAbilityConfig
{
    public WeaponCalculateDamageAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { var _j = _buf["attack"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  Attack = _j; } } else { Attack = null; } }
    }

    public static WeaponCalculateDamageAbilityConfig DeserializeWeaponCalculateDamageAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.WeaponCalculateDamageAbilityConfig(_buf);
    }

    public readonly int? Attack;
   
    public const int __ID__ = 1402799205;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "attack:" + Attack + ","
        + "}";
    }
}
}

