
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Combat
{
public sealed partial class WeaponCooldownAbilityConfig : EquipmentAbilityConfig
{
    public WeaponCooldownAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
    }

    public static WeaponCooldownAbilityConfig DeserializeWeaponCooldownAbilityConfig(JSONNode _buf)
    {
        return new Gameplay.Combat.WeaponCooldownAbilityConfig(_buf);
    }

    public readonly float Cooldown;
   
    public const int __ID__ = -934850733;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "cooldown:" + Cooldown + ","
        + "}";
    }
}
}

