
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig
{
public sealed partial class color32 : Luban.BeanBase
{
    public color32(JSONNode _buf) 
    {
        { if(!_buf["r"].IsNumber) { throw new SerializationException(); }  R = _buf["r"]; }
        { if(!_buf["g"].IsNumber) { throw new SerializationException(); }  G = _buf["g"]; }
        { if(!_buf["b"].IsNumber) { throw new SerializationException(); }  B = _buf["b"]; }
        { if(!_buf["a"].IsNumber) { throw new SerializationException(); }  A = _buf["a"]; }
    }

    public static color32 Deserializecolor32(JSONNode _buf)
    {
        return new color32(_buf);
    }

    public readonly byte R;
    public readonly byte G;
    public readonly byte B;
    public readonly byte A;
   
    public const int __ID__ = 949545218;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "r:" + R + ","
        + "g:" + G + ","
        + "b:" + B + ","
        + "a:" + A + ","
        + "}";
    }
}
}

