
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public abstract partial class EquipmentLevelConfig : Luban.BeanBase
{
    public EquipmentLevelConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["lst_ability"]; if(!__json0.IsArray) { throw new SerializationException(); } LstAbility = new System.Collections.Generic.List<EquipmentAbilityConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { EquipmentAbilityConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.EquipmentAbilityConfig.DeserializeEquipmentAbilityConfig(__e0);  }  LstAbility.Add(__v0); }   }
    }

    public static EquipmentLevelConfig DeserializeEquipmentLevelConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "ArmorLevelConfig": return new ArmorLevelConfig(_buf);
            case "SwordLevelConfig": return new SwordLevelConfig(_buf);
            case "BowLevelConfig": return new BowLevelConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Level;
    public readonly string Name;
    public readonly System.Collections.Generic.List<EquipmentAbilityConfig> LstAbility;
   

    public virtual void ResolveRef(Tables tables)
    {
        foreach (var _e in LstAbility) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "}";
    }
}

}

