
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class EquipmentConfig : Luban.BeanBase
{
    public EquipmentConfig(JSONNode _buf) 
    {
        { if(!_buf["config_id"].IsString) { throw new SerializationException(); }  ConfigId = _buf["config_id"]; }
        { var __json0 = _buf["lst_level_config"]; if(!__json0.IsArray) { throw new SerializationException(); } LstLevelConfig = new System.Collections.Generic.List<EquipmentLevelConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { EquipmentLevelConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.EquipmentLevelConfig.DeserializeEquipmentLevelConfig(__e0);  }  LstLevelConfig.Add(__v0); }   }
    }

    public static EquipmentConfig DeserializeEquipmentConfig(JSONNode _buf)
    {
        return new EquipmentConfig(_buf);
    }

    public readonly string ConfigId;
    public readonly System.Collections.Generic.List<EquipmentLevelConfig> LstLevelConfig;
   
    public const int __ID__ = -824956336;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstLevelConfig) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "lstLevelConfig:" + Luban.StringUtil.CollectionToString(LstLevelConfig) + ","
        + "}";
    }
}

}

