
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public abstract partial class MarbleAbilityConfig : Luban.BeanBase
{
    public MarbleAbilityConfig(JSONNode _buf) 
    {
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
    }

    public static MarbleAbilityConfig DeserializeMarbleAbilityConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "MarbleCloseToTargetAbilityConfig": return new MarbleCloseToTargetAbilityConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Priority;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "}";
    }
}

}

