
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class MarbleCloseToTargetAbilityConfig : MarbleAbilityConfig
{
    public MarbleCloseToTargetAbilityConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["close_distance"].IsNumber) { throw new SerializationException(); }  CloseDistance = _buf["close_distance"]; }
    }

    public static MarbleCloseToTargetAbilityConfig DeserializeMarbleCloseToTargetAbilityConfig(JSONNode _buf)
    {
        return new MarbleCloseToTargetAbilityConfig(_buf);
    }

    public readonly float CloseDistance;
   
    public const int __ID__ = 551835301;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "priority:" + Priority + ","
        + "closeDistance:" + CloseDistance + ","
        + "}";
    }
}

}

