
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class MarbleConfig : Luban.BeanBase
{
    public MarbleConfig(JSONNode _buf) 
    {
        { if(!_buf["config_id"].IsString) { throw new SerializationException(); }  ConfigId = _buf["config_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["lst_level_config"]; if(!__json0.IsArray) { throw new SerializationException(); } LstLevelConfig = new System.Collections.Generic.List<MarbleLevelConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { MarbleLevelConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.MarbleLevelConfig.DeserializeMarbleLevelConfig(__e0);  }  LstLevelConfig.Add(__v0); }   }
    }

    public static MarbleConfig DeserializeMarbleConfig(JSONNode _buf)
    {
        return new MarbleConfig(_buf);
    }

    public readonly string ConfigId;
    public readonly string Name;
    public readonly System.Collections.Generic.List<MarbleLevelConfig> LstLevelConfig;
   
    public const int __ID__ = 1886786815;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstLevelConfig) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "name:" + Name + ","
        + "lstLevelConfig:" + Luban.StringUtil.CollectionToString(LstLevelConfig) + ","
        + "}";
    }
}

}

