
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace GameConfig
{
public partial class Tables
{
    public GameConfig.TbMarble TbMarble {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbMarble = new GameConfig.TbMarble(loader("gameconfig_tbmarble"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbMarble.ResolveRef(this);
    }
}

}
