
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace GameConfig
{
public partial class Tables
{
    public Gameplay.Combat.TbCombatBattlefield TbCombatBattlefield {get; }
    public Gameplay.Camp.TbCamp TbCamp {get; }
    public Gameplay.Combat.TbEquipment TbEquipment {get; }
    public Gameplay.Expedition.TbExpedition TbExpedition {get; }
    public Gameplay.Expedition.TbExpeditionEvent TbExpeditionEvent {get; }
    public Gameplay.Expedition.TbExpeditionCombatEncounter TbExpeditionCombatEncounter {get; }
    public Gameplay.Expedition.TbExpeditionRandomEventPool TbExpeditionRandomEventPool {get; }
    public Gameplay.Expedition.TbExpeditionEnvironment TbExpeditionEnvironment {get; }
    public Gameplay.Expedition.TbExpeditionRewardProfile TbExpeditionRewardProfile {get; }
    public Gameplay.Initial.TbInitial TbInitial {get; }
    public Gameplay.Combat.TbMarble TbMarble {get; }
    public Gameplay.Combat.TbProjectile TbProjectile {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCombatBattlefield = new Gameplay.Combat.TbCombatBattlefield(loader("gameplay_combat_tbcombatbattlefield"));
        TbCamp = new Gameplay.Camp.TbCamp(loader("gameplay_camp_tbcamp"));
        TbEquipment = new Gameplay.Combat.TbEquipment(loader("gameplay_combat_tbequipment"));
        TbExpedition = new Gameplay.Expedition.TbExpedition(loader("gameplay_expedition_tbexpedition"));
        TbExpeditionEvent = new Gameplay.Expedition.TbExpeditionEvent(loader("gameplay_expedition_tbexpeditionevent"));
        TbExpeditionCombatEncounter = new Gameplay.Expedition.TbExpeditionCombatEncounter(loader("gameplay_expedition_tbexpeditioncombatencounter"));
        TbExpeditionRandomEventPool = new Gameplay.Expedition.TbExpeditionRandomEventPool(loader("gameplay_expedition_tbexpeditionrandomeventpool"));
        TbExpeditionEnvironment = new Gameplay.Expedition.TbExpeditionEnvironment(loader("gameplay_expedition_tbexpeditionenvironment"));
        TbExpeditionRewardProfile = new Gameplay.Expedition.TbExpeditionRewardProfile(loader("gameplay_expedition_tbexpeditionrewardprofile"));
        TbInitial = new Gameplay.Initial.TbInitial(loader("gameplay_initial_tbinitial"));
        TbMarble = new Gameplay.Combat.TbMarble(loader("gameplay_combat_tbmarble"));
        TbProjectile = new Gameplay.Combat.TbProjectile(loader("gameplay_combat_tbprojectile"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCombatBattlefield.ResolveRef(this);
        TbCamp.ResolveRef(this);
        TbEquipment.ResolveRef(this);
        TbExpedition.ResolveRef(this);
        TbExpeditionEvent.ResolveRef(this);
        TbExpeditionCombatEncounter.ResolveRef(this);
        TbExpeditionRandomEventPool.ResolveRef(this);
        TbExpeditionEnvironment.ResolveRef(this);
        TbExpeditionRewardProfile.ResolveRef(this);
        TbInitial.ResolveRef(this);
        TbMarble.ResolveRef(this);
        TbProjectile.ResolveRef(this);
    }
}

}

