
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public partial class TbMarble
{
    private readonly System.Collections.Generic.Dictionary<string, MarbleConfig> _dataMap;
    private readonly System.Collections.Generic.List<MarbleConfig> _dataList;
    
    public TbMarble(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, MarbleConfig>();
        _dataList = new System.Collections.Generic.List<MarbleConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MarbleConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.MarbleConfig.DeserializeMarbleConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ConfigId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, MarbleConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MarbleConfig> DataList => _dataList;

    public MarbleConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MarbleConfig Get(string key) => _dataMap[key];
    public MarbleConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

