
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public sealed partial class ArmorLevelConfig : EquipmentLevelConfig
{
    public ArmorLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["defense"]; }
    }

    public static ArmorLevelConfig DeserializeArmorLevelConfig(JSONNode _buf)
    {
        return new GameConfig.ArmorLevelConfig(_buf);
    }

    public readonly int Hp;
    public readonly int Defense;
   
    public const int __ID__ = -1335417343;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "hp:" + Hp + ","
        + "defense:" + Defense + ","
        + "}";
    }
}

}

