
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public sealed partial class ArmorConfig : EquipmentConfig
{
    public ArmorConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["defense"]; }
    }

    public static ArmorConfig DeserializeArmorConfig(JSONNode _buf)
    {
        return new GameConfig.ArmorConfig(_buf);
    }

    public readonly int Hp;
    public readonly int Defense;
   
    public const int __ID__ = -982708153;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "slot:" + Slot + ","
        + "hp:" + Hp + ","
        + "defense:" + Defense + ","
        + "}";
    }
}

}

