
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public sealed partial class BowConfig : EquipmentConfig
{
    public BowConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["rotate_speed"].IsNumber) { throw new SerializationException(); }  RotateSpeed = _buf["rotate_speed"]; }
        { if(!_buf["shoot_type"].IsNumber) { throw new SerializationException(); }  ShootType = _buf["shoot_type"]; }
        { if(!_buf["arrow_count"].IsNumber) { throw new SerializationException(); }  ArrowCount = _buf["arrow_count"]; }
        { if(!_buf["arrow_interval"].IsNumber) { throw new SerializationException(); }  ArrowInterval = _buf["arrow_interval"]; }
        { if(!_buf["arrow_angle_step"].IsNumber) { throw new SerializationException(); }  ArrowAngleStep = _buf["arrow_angle_step"]; }
        { if(!_buf["aim_angle"].IsNumber) { throw new SerializationException(); }  AimAngle = _buf["aim_angle"]; }
    }

    public static BowConfig DeserializeBowConfig(JSONNode _buf)
    {
        return new GameConfig.BowConfig(_buf);
    }

    public readonly float Cooldown;
    public readonly float RotateSpeed;
    public readonly int ShootType;
    public readonly int ArrowCount;
    public readonly float ArrowInterval;
    public readonly float ArrowAngleStep;
    public readonly float AimAngle;
   
    public const int __ID__ = 241752594;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "slot:" + Slot + ","
        + "cooldown:" + Cooldown + ","
        + "rotateSpeed:" + RotateSpeed + ","
        + "shootType:" + ShootType + ","
        + "arrowCount:" + ArrowCount + ","
        + "arrowInterval:" + ArrowInterval + ","
        + "arrowAngleStep:" + ArrowAngleStep + ","
        + "aimAngle:" + AimAngle + ","
        + "}";
    }
}

}

