
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public abstract partial class EquipmentConfig : Luban.BeanBase
{
    public EquipmentConfig(JSONNode _buf) 
    {
        { if(!_buf["config_id"].IsString) { throw new SerializationException(); }  ConfigId = _buf["config_id"]; }
        { if(!_buf["slot"].IsNumber) { throw new SerializationException(); }  Slot = _buf["slot"]; }
    }

    public static EquipmentConfig DeserializeEquipmentConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "ArmorConfig": return new GameConfig.ArmorConfig(_buf);
            case "WeaponConfig": return new GameConfig.WeaponConfig(_buf);
            case "BowConfig": return new GameConfig.BowConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string ConfigId;
    public readonly int Slot;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "slot:" + Slot + ","
        + "}";
    }
}

}

