
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public sealed partial class MarbleLevelConfig : Luban.BeanBase
{
    public MarbleLevelConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["upgrade_exp"].IsNumber) { throw new SerializationException(); }  UpgradeExp = _buf["upgrade_exp"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["shield"]; }
        { if(!_buf["defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["defense"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["mass"].IsNumber) { throw new SerializationException(); }  Mass = _buf["mass"]; }
        { if(!_buf["scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["scale"]; }
        { var __json0 = _buf["lst_equipment"]; if(!__json0.IsArray) { throw new SerializationException(); } LstEquipment = new System.Collections.Generic.List<GameConfig.EquipAttachConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameConfig.EquipAttachConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.GameConfig.EquipAttachConfig.DeserializeEquipAttachConfig(__e0);  }  LstEquipment.Add(__v0); }   }
        { var __json0 = _buf["lst_ability"]; if(!__json0.IsArray) { throw new SerializationException(); } LstAbility = new System.Collections.Generic.List<GameConfig.MarbleAbilityConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameConfig.MarbleAbilityConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::GameConfig.GameConfig.MarbleAbilityConfig.DeserializeMarbleAbilityConfig(__e0);  }  LstAbility.Add(__v0); }   }
    }

    public static MarbleLevelConfig DeserializeMarbleLevelConfig(JSONNode _buf)
    {
        return new GameConfig.MarbleLevelConfig(_buf);
    }

    public readonly int Level;
    public readonly int UpgradeExp;
    public readonly int Attack;
    public readonly int Hp;
    public readonly int Shield;
    public readonly int Defense;
    public readonly float Speed;
    public readonly float Mass;
    public readonly float Scale;
    public readonly System.Collections.Generic.List<GameConfig.EquipAttachConfig> LstEquipment;
    public readonly System.Collections.Generic.List<GameConfig.MarbleAbilityConfig> LstAbility;
   
    public const int __ID__ = 135936719;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LstEquipment) { _e?.ResolveRef(tables); }
        foreach (var _e in LstAbility) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "upgradeExp:" + UpgradeExp + ","
        + "attack:" + Attack + ","
        + "hp:" + Hp + ","
        + "shield:" + Shield + ","
        + "defense:" + Defense + ","
        + "speed:" + Speed + ","
        + "mass:" + Mass + ","
        + "scale:" + Scale + ","
        + "lstEquipment:" + Luban.StringUtil.CollectionToString(LstEquipment) + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "}";
    }
}

}

