
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public partial class TbEquipment
{
    private readonly System.Collections.Generic.Dictionary<string, GameConfig.EquipmentConfig> _dataMap;
    private readonly System.Collections.Generic.List<GameConfig.EquipmentConfig> _dataList;
    
    public TbEquipment(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, GameConfig.EquipmentConfig>();
        _dataList = new System.Collections.Generic.List<GameConfig.EquipmentConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GameConfig.EquipmentConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.GameConfig.EquipmentConfig.DeserializeEquipmentConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ConfigId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, GameConfig.EquipmentConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GameConfig.EquipmentConfig> DataList => _dataList;

    public GameConfig.EquipmentConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameConfig.EquipmentConfig Get(string key) => _dataMap[key];
    public GameConfig.EquipmentConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

