
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public sealed partial class WeaponConfig : EquipmentConfig
{
    public WeaponConfig(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["is_damage_by_velocity"].IsBoolean) { throw new SerializationException(); }  IsDamageByVelocity = _buf["is_damage_by_velocity"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
    }

    public static WeaponConfig DeserializeWeaponConfig(JSONNode _buf)
    {
        return new GameConfig.WeaponConfig(_buf);
    }

    public readonly int Attack;
    public readonly bool IsDamageByVelocity;
    public readonly float Cooldown;
   
    public const int __ID__ = -2102124968;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "configId:" + ConfigId + ","
        + "slot:" + Slot + ","
        + "attack:" + Attack + ","
        + "isDamageByVelocity:" + IsDamageByVelocity + ","
        + "cooldown:" + Cooldown + ","
        + "}";
    }
}

}

