
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.GameConfig
{
public abstract partial class WeaponLevelConfig : EquipmentLevelConfig
{
    public WeaponLevelConfig(JSONNode _buf)  : base(_buf) 
    {
        { var _j = _buf["attack"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  Attack = _j; } } else { Attack = null; } }
        { if(!_buf["is_damage_by_velocity"].IsBoolean) { throw new SerializationException(); }  IsDamageByVelocity = _buf["is_damage_by_velocity"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
    }

    public static WeaponLevelConfig DeserializeWeaponLevelConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "SwordLevelConfig": return new GameConfig.SwordLevelConfig(_buf);
            case "BowLevelConfig": return new GameConfig.BowLevelConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int? Attack;
    public readonly bool IsDamageByVelocity;
    public readonly float Cooldown;
   

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lstAbility:" + Luban.StringUtil.CollectionToString(LstAbility) + ","
        + "attack:" + Attack + ","
        + "isDamageByVelocity:" + IsDamageByVelocity + ","
        + "cooldown:" + Cooldown + ","
        + "}";
    }
}

}

