
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace GameConfig.Gameplay.Camp
{
public partial class TbCamp
{
    private readonly System.Collections.Generic.Dictionary<string, Gameplay.Camp.CampConfig> _dataMap;
    private readonly System.Collections.Generic.List<Gameplay.Camp.CampConfig> _dataList;
    
    public TbCamp(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Gameplay.Camp.CampConfig>(count);
        _dataList = new System.Collections.Generic.List<Gameplay.Camp.CampConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Gameplay.Camp.CampConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::GameConfig.Gameplay.Camp.CampConfig.DeserializeCampConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CampConfigId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Gameplay.Camp.CampConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Gameplay.Camp.CampConfig> DataList => _dataList;

    public Gameplay.Camp.CampConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gameplay.Camp.CampConfig Get(string key) => _dataMap[key];
    public Gameplay.Camp.CampConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

